Autonomous
Team8334/TitanRobotics2024 pull request #5
Opened 2024-02-07 00:16 UTC by impossiblerocket

added autonomous (commented stuff in robot.java is for aiden to merge in his stuff later easily)

2024-02-07 02:21 UTC, thebuilder6 requested changes

2024-02-07 02:21 UTC, thebuilder6 commented on TitanRobotics2024/src/main/java/frc/robot/Auto/AutoMissionChooser.java
> +
Standardize the enum values to uppercase
EXAMPLE_MISSION

2024-02-07 02:21 UTC, thebuilder6 commented on TitanRobotics2024/src/main/java/frc/robot/Auto/AutoMissionChooser.java
> +                break;
Remove the unnecessary break statement, and make an informative error message
```
default:
   System.err.println("No valid auto mode found for " + mode);
   return Optional.empty();
```

2024-02-07 02:21 UTC, thebuilder6 commented on TitanRobotics2024/src/main/java/frc/robot/Robot.java
Consider removing all coments and unused code to reduce size to more managable levels

2024-02-07 02:21 UTC, thebuilder6 commented on TitanRobotics2024/src/main/java/frc/robot/Teleop/Teleop.java
Still not sure what this file/class is good for

2024-02-08 02:17 UTC, impossiblerocket commented on TitanRobotics2024/src/main/java/frc/robot/Auto/AutoMissionChooser.java
> +
better/ easier to read in the current state

2024-02-08 18:24 UTC, thebuilder6 approved these changes

2024-02-08 18:26 UTC, thebuilder6 commented on TitanRobotics2024/src/main/java/frc/robot/Auto/AutoMissionChooser.java
> +
I think the Constants and Enum values should have a way to differentiate them from other variables, but I have approved your changes

2024-02-08 22:22 UTC, merged